# Generated by Django 4.1 on 2022-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
