# Generated by Django 4.1 on 2022-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(help_text='kamroq soz bilan tarifla', max_length=221),
        ),
    ]
